name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:

env:
  IMAGE: registry.larbreapages.fr/larbreapages.fr

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.larbreapages.fr
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build --build-arg PREFIX_PATHS=true -t ${{ env.IMAGE }}:${GITHUB_SHA::8} .

      - name: Push the Docker image
        run: |
          docker tag ${{ env.IMAGE }}:${GITHUB_SHA::8} ${{ env.IMAGE }}:latest
          docker push ${{ env.IMAGE }}:${GITHUB_SHA::8}
          docker push ${{ env.IMAGE }}:latest

      - name: Deploy on docker swarm
        run: |
          curl -X POST https://portainer.larbreapages.fr/api/webhooks/2c015e6d-dc2d-4607-bdcd-77414f27bd38
